Added Scoreboard and UI frontend
LifeInvaders/game pull request #94
Opened 2021-06-18 18:51 UTC by juliencohenscali

2021-06-18 19:03 UTC, Renaud-Dov commented on Packages/manifest.json
> -    "com.unity.postprocessing": "3.0.3",
il manque le paquet postprocessing

2021-06-18 19:09 UTC, Renaud-Dov requested changes

2021-06-18 19:09 UTC, Renaud-Dov commented on ProjectSettings/ProjectSettings.asset
> -  companyName: LifeInvaders Production
Faut laisser le fichier ProjectSettings/ProjectSettings.asset intact

2021-06-18 19:09 UTC, Renaud-Dov commented on ProjectSettings/ProjectVersion.txt
> -m_EditorVersion: 2019.4.16f1
@Harsane  est-ce qu'il n'y aurait pas de pb à utiliser une version mineure supérieure 🤔  ?

2021-06-18 19:24 UTC, Renaud-Dov approved these changes
LGTM

2021-06-18 19:24 UTC, merged

2021-06-18 19:43 UTC, Harsane requested changes
Je propose qu'on ferme ce PR et qu'on transfère les fichiers autrement car ça m'a l'air un peu funky

2021-06-18 19:43 UTC, Harsane commented on ProjectSettings/ProjectVersion.txt
> -m_EditorVersion: 2019.4.16f1
Oula... 

Ca m'a l'air compliqué ^^

Mais y a pas que ça, y a aussi l'old input system qui est désactivé alors qu'en réalité il est encore plutôt présent :/

D'ailleurs il y a aussi des marqueurs de conflits dans les fichiers donc à mon avis pas sûr que ça compile.

Voilà ce que je propose: on transfère les fichiers importants hors-Github et quelqu'un d'autre push. Après Julien si tu veux tu peux reset ton fork pour remettre de l'ordre. Je préfère ne pas merge là perso

2021-06-18 20:24 UTC, Renaud-Dov commented
> Je propose qu'on ferme ce PR et qu'on transfère les fichiers autrement car ça m'a l'air un peu funky
> 
> Edit: Ah, ça a été merge... Bon si y a pas de conflits pas de soucis mais au pire on revert no probs

c'est corrigé, tkt pas @Harsane

2021-06-19 02:26 UTC, juliencohenscali commented
Ne t'inquietes pas @Harsane , le problème venait du fait que j'avais installer unity sur mon pc fixe, et comme un idiot j'ai installé une version plus récente de unity. En lancant le projet ça a du overwrite ce fameux fichier en inscrivant la version la plus récente utilisée (2019.4.24 ou quelque chose comme ca). Mais nos probs la totalité des modifs ont été faites sur mon pc portable ( où j'utilise bien la version commune 2019.4.16).
Bien cordialement les bgs